### ISSUE TITLE
3枚以上追加できない

### ISSUE THREAD

**Issue by monokemonoke** [enpitut2022/aoi-shiori#23]
現在のdevelopの状態だと3枚以上だと見切れてしまう問題がある
https://develop--aoi-shiori.netlify.app/

**Comment by monokemonoke** [comment]
カードを重ねるように動かすとバグる

**Comment by aktkszk000** [comment]
見切れる：最大幅を決めてauto-scrollなんたらをenableにすればいいらしい

**Comment by shosuke447** [comment]
overflow: scroll;で解決
